[package]
name = "Semester_Project_Rust_Rewrite"
version = "0.1.0"
authors = ["Glazzerino <fztmon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
