# Francisco Zamora Treviño A01570484
library(tidyverse)
covid <- read.csv("covid.csv")
options(device = "windows")
print(paste("Numero de países en base de datos:", length(levels(covid$location))))
mexico <- subset(covid,grepl("Mexico",covid$location))
mex muertes <- data.frame(mexico$date, méxico$total_deaths)
plot(mexico$date,mexico$total_deaths,type="o",xlab="Fecha",ylab="Muertes totales")
x11()
plot(mexico$date,mexico$new_cases,type="o",xlab="Fecha",ylab="Nuevos casos")
x11()
china <- subset(covid,grepl("China",covid$location))
plot(china$date,china$total_deaths,type="o",xlab="Fecha",ylab="Muertes totales")
x11()
plot(china$date,china$new_cases,type="o",xlab="Fecha",ylab="Nuevos casos")
write.csv(china,"China.csv")
write.csv(mexico,"Mexico.csv")
cat("ARCHIVOS ESCRITOS\n")

